name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleDebug assembleAndroidTest
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: app/build/outputs/apk
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: test android run \
                  --type instrumentation \
                  --app debug/app-debug.apk \
                  --test androidTest/debug/app-debug-androidTest.apk \
                  --device model=Nexus6P,version=26,locale=en,orientation=portrait
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
